# Site settings
title: Peter Nencka
email: nencka.2@osu.edu
description: > # this means to ignore newlines until "baseurl:"
Economics and baseball (not nessisarally in order) 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: peternka
github_username:  pnencka

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "PhD Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
