# Site settings
title: Ruslan Dautov
email: 
description: > 
     Shenzhen Unversity,
     Institute of Big Data Technology and Applications,
     College of Computer Science and Software Engineering,
     Office 614
     
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dautovri.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  dautovri

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research assistant"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
