# Site settings
title: Ranjan Jayapal Blog
email: ranjan.jayapal.us@gmail.com
description: > Computer Science Freak
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ranjanjayapal.github.io" # the base hostname & protocol for your site
twitter_username: RJ7_logan
github_username:  ranjanjayapal

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"
